packages:
  - packages/**
  - "!**/test/**"
ignoredBuiltDependencies:
  - esbuild
catalog:
  "@changesets/cli": ^2.28.1
  "@types/node": ^22.13.14
  "@vitejs/plugin-vue": ^5.2.1
  "@vue/tsconfig": ^0.7.0
  naive-ui: ^2.41.0
  ol: ^10.4.0
  typescript: ~5.7.2
  vite: ^6.2.0
  vite-plugin-dts: ^4.5.3
  vue: ^3.5.13
  vue-tsc: ^2.2.4
