packages:
  - packages/**
  - '!**/test/**'
  - '!**/public/**'
  - '!**/guide/**'
catalog:
  '@antfu/eslint-config': ^4.12.0
  '@changesets/cli': 2.29.8
  '@css-render/vue3-ssr': ^0.15.14
  '@turf/turf': 7.2.0
  '@types/node': ^22.13.14
  '@unocss/eslint-plugin': 66.1.0-beta.11
  '@vitejs/plugin-vue': 6.0.1
  '@vitest/coverage-v8': ^3.1.1
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.7.0
  '@vueuse/core': ^13.1.0
  ant-design-vue: ^4.2.6
  cesium: ^1.128.0
  element-plus: ^2.11.5
  esbuild: 0.25.11
  eslint: ^9.24.0
  globby: ^14.1.0
  jsdom: ^26.0.0
  naive-ui: ^2.41.0
  ol: ^10.5.0
  sass-embedded: ^1.86.3
  tsdown: 0.11.3
  typescript: ~5.7.2
  unocss: 66.5.4
  vite: npm:rolldown-vite@latest
  vite-plugin-css-injected-by-js: ^3.5.2
  vite-plugin-dts: ^4.5.3
  vite-plugin-externals: ^0.6.2
  vitepress: ^2.0.0-alpha.12
  vitest: ^3.1.1
  vue: ^3.5.13
  vue-tsc: ^2.2.4
ignoredBuiltDependencies:
  - esbuild
