packages:
  - packages/**
  - '!**/test/**'
  - '!**/public/**'
ignoredBuiltDependencies:
  - esbuild
catalog:
  '@changesets/cli': ^2.28.1
  '@types/node': ^22.13.14
  '@vitejs/plugin-vue': ^5.2.1
  '@vue/tsconfig': ^0.7.0
  naive-ui: ^2.41.0
  ol: 10.5.0
  typescript: ~5.7.2
  vite: ^6.2.0
  vite-plugin-dts: ^4.5.3
  vue: ^3.5.13
  vue-tsc: ^2.2.4
  '@vueuse/core': ^13.0.0
  unocss: ^66.1.0-beta.8
  vitepress: ^2.0.0-alpha.4
  '@css-render/vue3-ssr': ^0.15.14
  '@turf/turf': 7.2.0
  sass-embedded: ^1.86.3
  vite-plugin-css-injected-by-js: ^3.5.2
