/**
 * Generated by tsnapi — public API snapshot of `@summeruse/ol`
 */
// #region Interfaces
export interface ClickContext {
  map: OLMap;
  coordinate: Coordinate;
  pixel: Pixel;
  feature?: FeatureLike;
  layer: LayerLike;
}
export interface ContextmenuItem extends ContextmenuItemBase {
  children?: Array<ContextmenuItem>;
}
export interface ContextmenuItemBase {
  label: ((_: ContextmenuItemParams) => VNodeChild) | string;
  visible?: ((_: ContextmenuItemParams) => boolean) | boolean;
  disabled?: ((_: ContextmenuItemParams) => boolean) | boolean;
  action?: (_: ContextmenuItemParams) => void;
  divided?: boolean;
  icon?: ((_: ContextmenuItemParams) => VNodeChild) | string;
  order?: number;
  key?: string | number;
  [key: string]: any;
}
export interface ContextmenuOption extends ContextmenuOptionBase {
  children?: Array<ContextmenuOption>;
}
export interface ContextmenuOptionBase {
  label: string | (() => VNodeChild);
  visible?: boolean;
  disabled?: boolean;
  action: () => void;
  divided?: boolean;
  icon?: string | (() => VNodeChild);
  order?: number;
  key?: string | number;
  [key: string]: any;
}
export interface ContextmenuPosition {
  x: number;
  y: number;
}
export interface CreateBingLayerOptions {
  name: string;
  key: string;
  layerOptions?: TileLayerOptions;
  sourceOptions?: BingMapsSourceOptions;
}
export interface CreateOpenStreetMapLayerOptions {
  layerOptions?: TileLayerOptions;
  sourceOptions?: OpenStreetMapSourceOptions;
}
export interface CreateTianDiTuUrlOptions {
  url?: string;
  key: string;
  type: T_MAP_TYPE;
  projection?: 'EPSG:3857' | 'EPSG:4326';
}
export interface DrawLineStringOptions {
  defaultCoordinates?: Coordinate[][];
  deletePointLabel?: VNode;
  deleteFeatureLabel?: VNode;
  style?: Style;
  styleOptions?: StyleOptions;
  drawStyle?: Style;
  drawStyleOptions?: StyleOptions;
  modifyStyle?: Style;
  modifyStyleOptions?: StyleOptions;
  zIndex?: number;
  size?: number;
}
export interface DrawPolygonOptions {
  defaultCoordinates?: Coordinate[][][];
  deletePointLabel?: VNode;
  deleteFeatureLabel?: VNode;
  style?: Style;
  styleOptions?: StyleOptions;
  drawStyleOptions?: StyleOptions;
  modifyStyleOptions?: StyleOptions;
  drawStyle?: Style;
  modifyStyle?: Style;
  zIndex?: number;
  size?: number;
}
export interface FeatureOptions {
  style?: Style;
  styleOptions?: StyleOptions;
  geometry?: Geometry;
  [key: string]: any;
}
export interface OlMapEmits {
  'update:zoom': [number];
  'update:center': [Coordinate];
  'update:rotation': [number];
  'changeResolution': [ObjectEvent];
  'changeRotation': [ObjectEvent];
  'changeCenter': [ObjectEvent];
  'moveend': [MapEvent];
  'movestart': [MapEvent];
}
export interface OlMapProps {
  olMap?: Map;
  center?: Coordinate;
  rotation?: number;
  zoom?: number;
  minZoom?: number;
  maxZoom?: number;
  constrainResolution?: boolean;
  projection?: ProjectionLike;
  extent?: Extent;
  showZoom?: boolean;
  showAttribution?: boolean;
  showRotate?: boolean;
  showFullScreen?: boolean;
  showOverview?: boolean;
  showScale?: boolean;
  dragPan?: boolean;
  mouseWheelZoom?: boolean;
  doubleClickZoom?: boolean;
  pinchRotate?: boolean;
  pinchZoom?: boolean;
  altShiftDragRotate?: boolean;
}
export interface PointermovePosition {
  x: number;
  y: number;
}
export interface UseClickHandlerOptions<T extends Option$1 = Option$1> {
  mapRef: MaybeRefOrGetter<OLMap | undefined>;
  items: MaybeRefOrGetter<ClickConfigList<T>>;
  type: ClickEventType;
}
export interface UseGraticuleOptions {
  olMap: MaybeRef<Map | null | undefined>;
  graticuleOptions?: GraticuleOptions;
  defaultShow?: boolean;
}
export interface UsePointermoveOptions<T extends Option = Option> {
  mapRef: MaybeRefOrGetter<OLMap | undefined>;
  items: MaybeRefOrGetter<PointermoveList<T>>;
  forceUpdate?: boolean;
}
// #endregion

// #region Types
export type _CircleOptions = ConstructorParameters<typeof Circle$1>[0];
export type _GraticuleOptions = ConstructorParameters<typeof Graticule>[0];
export type _StyleOptions = ConstructorParameters<typeof Style>[0];
export type _TextOptions = ConstructorParameters<typeof Text>[0];
export type _VectorLayerOptions<T extends Geometry = Geometry> = ConstructorParameters<typeof VectorLayer<VectorSource<Feature<T>>>>[0];
export type _VectorSourceOptions<T extends Geometry = Geometry> = ConstructorParameters<typeof VectorSource<Feature<T>>>[0];
export type _WebGLVectorLayerOptions<T extends Geometry = Geometry> = ConstructorParameters<typeof WebGLVectorLayer<VectorSource<Feature<T>>>>[0];
export type BingMapsSourceOptions = Partial<ConstructorParameters<typeof BingMaps>[0]>;
export type CanvasLayerOptions = ConstructorParameters<typeof Layer>[0];
export type CircleOptions = _CircleOptions & {
  fillOptions?: FillOptions;
  strokeOptions?: StrokeOptions;
};
export type ClickConfig<T extends Option$1> = {
  hitTolerance?: number;
  priority?: number;
  visible?: (_: ClickContext) => boolean | undefined | void;
  handler: (_: ClickContext) => void;
} & T;
export type ClickConfigList<T extends Option$1> = ClickConfig<T>[];
export type ClickEventType = 'click' | 'dblclick' | 'singleclick';
export type ContextmenuList = ContextmenuItem[];
export type ContextmenuOptions = ContextmenuOption[];
export type createHeatmapLayerOptions = HeatmapLayerOptions & {
  sourceOptions?: VectorSourceOptions;
};
export type CreateTianDiTuLayerOptions = CreateTianDiTuUrlOptions & {
  layerOptions?: TileLayerOptions;
  sourceOptions?: XYZ_SourceOptions;
};
export type FillOptions = ConstructorParameters<typeof Fill>[0];
export type ForEachFeatureAtPixelCallbackOptions = Parameters<Parameters<OLMap['forEachFeatureAtPixel']>[1]>;
export type GraticuleOptions = _GraticuleOptions & {
  strokeStyleOption?: StrokeOptions;
  labelStyleOption?: TextOptions;
  latLabelStyleOption?: TextOptions;
  lonLabelStyleOption?: TextOptions;
};
export type HeatmapLayerOptions = ConstructorParameters<typeof HeatmapLayer>[0];
export type IconOptions = ConstructorParameters<typeof Icon>[0];
export type ImageTileSourceOptions = ConstructorParameters<typeof ImageTileSource>[0];
export type LayerLike = ForEachFeatureAtPixelCallbackOptions[1];
export type OlMapInst = InstanceType<typeof _default>;
export type OpenStreetMapSourceOptions = Partial<ConstructorParameters<typeof OSM>[0]>;
export type PMTilesLayerOptions = TileLayerOptions & {
  url: string;
  sourceOptions?: ImageTileSourceOptions;
};
export type PointermoveItem<T extends Option = Option> = {
  content?: ((_: PointermoveContentParams) => VNodeChild) | string;
  visible?: ((_: PointermoveContentParams) => boolean | undefined | void) | boolean;
  offset?: {
    x?: number;
    y?: number;
  };
  priority?: number;
  cursor?: Cursor | ((_: PointermoveContentParams) => Cursor);
  fixedFeatureCenter?: boolean;
  hitTolerance?: number;
} & T;
export type PointermoveList<T extends Option = Option> = PointermoveItem<T>[];
export type ProjectionLike = 'EPSG:3857' | 'EPSG:4326' | 'EPSG:3395';
export type StrokeOptions = ConstructorParameters<typeof Stroke>[0];
export type StyleOptions = _StyleOptions & {
  fillOptions?: FillOptions;
  strokeOptions?: StrokeOptions;
  iconOptions?: IconOptions;
  circleOptions?: CircleOptions;
  textOptions?: TextOptions;
};
export type T_MAP_TYPE = 'vec' | 'cva' | 'img' | 'cia' | 'ter' | 'cta' | 'ibo';
export type TextOptions = _TextOptions & {
  fillOptions?: FillOptions;
  strokeOptions?: StrokeOptions;
  backgroundFillOptions?: FillOptions;
  backgroundStrokeOptions?: StrokeOptions;
};
export type TileLayerOptions = Partial<ConstructorParameters<typeof Tile>[0]>;
export type UseContextmenuFn = (..._: UseContextmenuParams) => UseContextmenuReturn;
export type UseContextmenuParams = Parameters<typeof useContextmenu>;
export type UseContextmenuReturn = ReturnType<typeof useContextmenu>;
export type UseGraticuleReturn = ReturnType<typeof useGraticule>;
export type UseMapClickHandlerReturn = ReturnType<typeof useMapClickHandler>;
export type UseMapClickReturn = ReturnType<typeof useMapClick>;
export type UsePointermoveFn<T extends Option> = (..._: UsePointermoveParams<T>) => UsePointermoveReturn;
export type UsePointermoveParams<T extends Option> = Parameters<typeof usePointermove<T>>;
export type UsePointermoveReturn = ReturnType<typeof usePointermove>;
export type VectorLayerOptions<T extends Geometry = Geometry> = _VectorLayerOptions<T> & {
  styleOptions?: StyleOptions;
  sourceOptions?: VectorSourceOptions<T>;
};
export type VectorSourceOptions<T extends Geometry = Geometry> = _VectorSourceOptions<T>;
export type WebGLVectorLayerOptions<T extends Geometry = Geometry> = _WebGLVectorLayerOptions<T> & {
  style: FlatStyleLike;
  sourceOptions?: VectorSourceOptions<T>;
};
export type XYZ_SourceOptions = Partial<ConstructorParameters<typeof XYZ>[0]>;
export type XYZLayerOptions = TileLayerOptions & {
  sourceOptions: XYZ_SourceOptions;
};
// #endregion

// #region Functions
export declare function angleToRotation(_: number): number;
export declare function createBingLayer({
  name,
  key,
  layerOptions,
  sourceOptions
}: CreateBingLayerOptions): Tile<ol_source0.Tile<ol0.Tile>>;
export declare function createCanvasLayer(_: OLMap, _: (_: FrameState) => {
  imageBitmap: ImageBitmap;
  dpi: number;
} | boolean | undefined, _?: CanvasLayerOptions): {
  layer: Layer<Source, ol_renderer_Layer0.default<any>, {
    [x: string]: any;
  }>;
};
export declare function createCircle(_: Coordinate, _: number): Circle;
export declare function createCircleFeature(_: Coordinate, _: number, _?: FeatureOptions): Feature<Circle>;
export declare function createCircleStyle(_: CircleOptions): Circle$1;
export declare function createFeature(_?: FeatureOptions): Feature<Geometry, {
  [x: string]: any;
}>;
export declare function createHeatmapLayer(_?: createHeatmapLayerOptions): {
  layer: HeatmapLayer<Feature<Geometry, {
    [x: string]: any;
  }>, VectorSource<Feature<Geometry, {
    [x: string]: any;
  }>>>;
  source: VectorSource<Feature<Geometry, {
    [x: string]: any;
  }>>;
};
export declare function createLineString(_: Coordinate[]): LineString;
export declare function createLineStringFeature(_: Coordinate[], _?: FeatureOptions): Feature<LineString>;
export declare function createMultiLineString(_: Coordinate[][]): MultiLineString;
export declare function createMultiLineStringFeature(_: Coordinate[][], _?: FeatureOptions): Feature<MultiLineString>;
export declare function createMultiPoint(_: Coordinate[]): MultiPoint;
export declare function createMultiPointFeature(_: Coordinate[], _?: FeatureOptions): Feature<MultiPoint>;
export declare function createMultiPolygon(_: Coordinate[][][]): MultiPolygon;
export declare function createMultiPolygonFeature(_: Coordinate[][][], _?: FeatureOptions): Feature<MultiPolygon>;
export declare function createOpenStreetMapLayer(_?: CreateOpenStreetMapLayerOptions): Tile<ol_source0.Tile<ol0.Tile>>;
export declare function createPMTilesLayer(_: PMTilesLayerOptions): Tile<ImageTileSource>;
export declare function createPoint(_: Coordinate): Point;
export declare function createPointFeature(_: Coordinate, _?: FeatureOptions): Feature<Point>;
export declare function createPolygon(_: Coordinate[][]): Polygon;
export declare function createPolygonFeature(_: Coordinate[][], _?: FeatureOptions): Feature<Polygon>;
export declare function createStyle(_: StyleOptions): Style;
export declare function createTextStyle(_: TextOptions): Text;
export declare function createTianDiTuLayer(_: CreateTianDiTuLayerOptions): Tile<ol_source0.Tile<ol0.Tile>>;
export declare function createTianDiTuUrl(_: CreateTianDiTuUrlOptions): string;
export declare function createTileGrid(_?: Projection | string): ol_tilegrid0.TileGrid | undefined;
export declare function createVectorLayer<T extends Geometry = Geometry>(_?: VectorLayerOptions<T>): {
  source: VectorSource<Feature<T, {
    [x: string]: any;
  }>>;
  layer: VectorLayer<VectorSource<Feature<T, {
    [x: string]: any;
  }>>, Feature<T, {
    [x: string]: any;
  }>>;
};
export declare function createVectorSource<T extends Geometry = Geometry>(_?: VectorSourceOptions<T>): VectorSource<Feature<T, {
  [x: string]: any;
}>>;
export declare function createWebGLVectorLayer<T extends Geometry = Geometry>(_: WebGLVectorLayerOptions<T>): {
  source: VectorSource<Feature<T, {
    [x: string]: any;
  }>>;
  layer: WebGLVectorLayer<VectorSource<Feature<T, {
    [x: string]: any;
  }>>, Feature<T, {
    [x: string]: any;
  }>>;
};
export declare function createXYZLayer({
  sourceOptions,
  ...layerOptions
}: XYZLayerOptions): Tile<XYZ>;
export declare function EPSG_3857ExtentToEPSG_4326(_: Extent): Extent;
export declare function EPSG_3857ToEPSG_4326(_: Coordinate): Coordinate;
export declare function EPSG_4326ExtentToEPSG_3857(_: Extent): Extent;
export declare function EPSG_4326ToEPSG_3857(_: Coordinate): Coordinate;
export declare function formatAngle(_: number): number;
export declare function formatRotation(_: number): number;
export declare function kmToNauticalMiles(_: number): number;
export declare function nauticalMilesToKm(_: number): number;
export declare function registerEPSG_3395(): void;
export declare function rotationToAngle(_: number): number;
export declare function useContextmenu(_: MaybeRefOrGetter<OLMap | undefined>, _: MaybeRefOrGetter<ContextmenuList>): {
  visible: vue20.ComputedRef<boolean>;
  position: vue20.ComputedRef<{
    x: number;
    y: number;
  }>;
  feature: vue20.ComputedRef<FeatureLike | undefined>;
  options: vue20.ComputedRef<{
    [x: string]: any;
    children?: any[] | undefined;
    label: string | (() => VNodeChild);
    visible?: boolean | undefined;
    disabled?: boolean | undefined;
    action: () => void;
    divided?: boolean | undefined;
    icon?: string | (() => VNodeChild) | undefined;
    order?: number | undefined;
    key?: string | number | undefined;
  }[]>;
  coordinate: vue20.ComputedRef<Coordinate | undefined>;
  hide: () => void;
};
export declare function useDrawLineString(_: OLMap, _: DrawLineStringOptions): {
  inDraw: vue20.Ref<boolean, boolean>;
  start: () => void;
  stop: () => void;
  clear: () => void;
  setFeatures: (_: Coordinate[][]) => void;
  reset: () => void;
  features: vue20.Ref<{
    on: ol_Feature5.FeatureOnSignature<ol_events13.EventsKey>;
    once: ol_Feature5.FeatureOnSignature<ol_events13.EventsKey>;
    un: ol_Feature5.FeatureOnSignature<void>;
    clone: () => Feature<LineString, {
      [x: string]: any;
    }>;
    getGeometry: () => LineString | undefined;
    getId: () => number | string | undefined;
    getGeometryName: () => string;
    getStyle: () => ol_style_Style5.StyleLike | undefined;
    getStyleFunction: () => ol_style_Style5.StyleFunction | undefined;
    setGeometry: (geometry: LineString | undefined) => void;
    setStyle: (style?: ol_style_Style5.StyleLike) => void;
    setId: (id: number | string | undefined) => void;
    setGeometryName: (name: string) => void;
    get: (key: string) => any;
    getKeys: () => Array<string>;
    getProperties: () => NoInfer<{
      [x: string]: any;
    }>;
    getPropertiesInternal: () => Partial<NoInfer<{
      [x: string]: any;
    }>> | null;
    hasProperties: () => boolean;
    notify: (key: string, oldValue: any) => void;
    addChangeListener: (key: string, listener: ol_events13.Listener) => void;
    removeChangeListener: (key: string, listener: ol_events13.Listener) => void;
    set: (key: string, value: any, silent?: boolean) => void;
    setProperties: (values: Partial<NoInfer<{
      [x: string]: any;
    }>>, silent?: boolean) => void;
    unset: (key: string, silent?: boolean) => void;
    changed: () => void;
    getRevision: () => number;
    addEventListener: (type: string, listener: ol_events13.Listener) => void;
    dispatchEvent: (event: ol_events_Event1.default | string) => boolean | undefined;
    getListeners: (type: string) => Array<ol_events13.Listener> | undefined;
    hasListener: (type?: string) => boolean;
    removeEventListener: (type: string, listener: ol_events13.Listener) => void;
    dispose: () => void;
  }[], Feature<LineString, {
    [x: string]: any;
  }>[] | {
    on: ol_Feature5.FeatureOnSignature<ol_events13.EventsKey>;
    once: ol_Feature5.FeatureOnSignature<ol_events13.EventsKey>;
    un: ol_Feature5.FeatureOnSignature<void>;
    clone: () => Feature<LineString, {
      [x: string]: any;
    }>;
    getGeometry: () => LineString | undefined;
    getId: () => number | string | undefined;
    getGeometryName: () => string;
    getStyle: () => ol_style_Style5.StyleLike | undefined;
    getStyleFunction: () => ol_style_Style5.StyleFunction | undefined;
    setGeometry: (geometry: LineString | undefined) => void;
    setStyle: (style?: ol_style_Style5.StyleLike) => void;
    setId: (id: number | string | undefined) => void;
    setGeometryName: (name: string) => void;
    get: (key: string) => any;
    getKeys: () => Array<string>;
    getProperties: () => NoInfer<{
      [x: string]: any;
    }>;
    getPropertiesInternal: () => Partial<NoInfer<{
      [x: string]: any;
    }>> | null;
    hasProperties: () => boolean;
    notify: (key: string, oldValue: any) => void;
    addChangeListener: (key: string, listener: ol_events13.Listener) => void;
    removeChangeListener: (key: string, listener: ol_events13.Listener) => void;
    set: (key: string, value: any, silent?: boolean) => void;
    setProperties: (values: Partial<NoInfer<{
      [x: string]: any;
    }>>, silent?: boolean) => void;
    unset: (key: string, silent?: boolean) => void;
    changed: () => void;
    getRevision: () => number;
    addEventListener: (type: string, listener: ol_events13.Listener) => void;
    dispatchEvent: (event: ol_events_Event1.default | string) => boolean | undefined;
    getListeners: (type: string) => Array<ol_events13.Listener> | undefined;
    hasListener: (type?: string) => boolean;
    removeEventListener: (type: string, listener: ol_events13.Listener) => void;
    dispose: () => void;
  }[]>;
  coordinates: vue20.ComputedRef<Coordinate[][]>;
  destroy: () => void;
};
export declare function useDrawPolygon(_: OLMap, _: DrawPolygonOptions): {
  inDraw: vue20.Ref<boolean, boolean>;
  start: () => void;
  stop: () => void;
  clear: () => void;
  setFeatures: (_?: Coordinate[][][]) => void;
  reset: () => void;
  features: vue20.Ref<{
    on: ol_Feature5.FeatureOnSignature<ol_events13.EventsKey>;
    once: ol_Feature5.FeatureOnSignature<ol_events13.EventsKey>;
    un: ol_Feature5.FeatureOnSignature<void>;
    clone: () => Feature<Polygon, {
      [x: string]: any;
    }>;
    getGeometry: () => Polygon | undefined;
    getId: () => number | string | undefined;
    getGeometryName: () => string;
    getStyle: () => ol_style_Style5.StyleLike | undefined;
    getStyleFunction: () => ol_style_Style5.StyleFunction | undefined;
    setGeometry: (geometry: Polygon | undefined) => void;
    setStyle: (style?: ol_style_Style5.StyleLike) => void;
    setId: (id: number | string | undefined) => void;
    setGeometryName: (name: string) => void;
    get: (key: string) => any;
    getKeys: () => Array<string>;
    getProperties: () => NoInfer<{
      [x: string]: any;
    }>;
    getPropertiesInternal: () => Partial<NoInfer<{
      [x: string]: any;
    }>> | null;
    hasProperties: () => boolean;
    notify: (key: string, oldValue: any) => void;
    addChangeListener: (key: string, listener: ol_events13.Listener) => void;
    removeChangeListener: (key: string, listener: ol_events13.Listener) => void;
    set: (key: string, value: any, silent?: boolean) => void;
    setProperties: (values: Partial<NoInfer<{
      [x: string]: any;
    }>>, silent?: boolean) => void;
    unset: (key: string, silent?: boolean) => void;
    changed: () => void;
    getRevision: () => number;
    addEventListener: (type: string, listener: ol_events13.Listener) => void;
    dispatchEvent: (event: ol_events_Event1.default | string) => boolean | undefined;
    getListeners: (type: string) => Array<ol_events13.Listener> | undefined;
    hasListener: (type?: string) => boolean;
    removeEventListener: (type: string, listener: ol_events13.Listener) => void;
    dispose: () => void;
  }[], Feature<Polygon, {
    [x: string]: any;
  }>[] | {
    on: ol_Feature5.FeatureOnSignature<ol_events13.EventsKey>;
    once: ol_Feature5.FeatureOnSignature<ol_events13.EventsKey>;
    un: ol_Feature5.FeatureOnSignature<void>;
    clone: () => Feature<Polygon, {
      [x: string]: any;
    }>;
    getGeometry: () => Polygon | undefined;
    getId: () => number | string | undefined;
    getGeometryName: () => string;
    getStyle: () => ol_style_Style5.StyleLike | undefined;
    getStyleFunction: () => ol_style_Style5.StyleFunction | undefined;
    setGeometry: (geometry: Polygon | undefined) => void;
    setStyle: (style?: ol_style_Style5.StyleLike) => void;
    setId: (id: number | string | undefined) => void;
    setGeometryName: (name: string) => void;
    get: (key: string) => any;
    getKeys: () => Array<string>;
    getProperties: () => NoInfer<{
      [x: string]: any;
    }>;
    getPropertiesInternal: () => Partial<NoInfer<{
      [x: string]: any;
    }>> | null;
    hasProperties: () => boolean;
    notify: (key: string, oldValue: any) => void;
    addChangeListener: (key: string, listener: ol_events13.Listener) => void;
    removeChangeListener: (key: string, listener: ol_events13.Listener) => void;
    set: (key: string, value: any, silent?: boolean) => void;
    setProperties: (values: Partial<NoInfer<{
      [x: string]: any;
    }>>, silent?: boolean) => void;
    unset: (key: string, silent?: boolean) => void;
    changed: () => void;
    getRevision: () => number;
    addEventListener: (type: string, listener: ol_events13.Listener) => void;
    dispatchEvent: (event: ol_events_Event1.default | string) => boolean | undefined;
    getListeners: (type: string) => Array<ol_events13.Listener> | undefined;
    hasListener: (type?: string) => boolean;
    removeEventListener: (type: string, listener: ol_events13.Listener) => void;
    dispose: () => void;
  }[]>;
  coordinates: vue20.ComputedRef<Coordinate[][][]>;
  destroy: () => void;
};
export declare function useGraticule(_: UseGraticuleOptions): {
  showGraticule: Ref<boolean, boolean>;
};
export declare function useMapClick<T extends Option$1 = Option$1>(_: MaybeRefOrGetter<OLMap | undefined>, _: ClickEventType): {
  add: (_: string, _: ClickConfigList<T>) => void;
  remove: (_: string) => void;
};
export declare function useMapClickHandler<T extends Option$1 = Option$1>(_: UseClickHandlerOptions<T>): void;
export declare function useOlMap(): Map | undefined;
export declare function usePointermove<T extends Option>({
  mapRef,
  items,
  forceUpdate
}: UsePointermoveOptions<T>): {
  visible: vue20.ComputedRef<boolean>;
  position: vue20.ComputedRef<{
    x: number;
    y: number;
  }>;
  offset: vue20.ComputedRef<{
    x: number;
    y: number;
  }>;
  originalPosition: vue20.ComputedRef<{
    x: number;
    y: number;
  }>;
  feature: vue20.ComputedRef<FeatureLike | undefined>;
  content: vue20.ComputedRef<string | (() => VNodeChild) | undefined>;
  originalCoordinate: vue20.ComputedRef<Coordinate | undefined>;
  coordinate: vue20.ComputedRef<Coordinate | undefined>;
  option: vue20.ComputedRef<T | undefined>;
  hide: () => void;
};
export declare function useSwitchBaseLayer(_: {
  olMap: Map;
  defaultLayerName?: string;
  layers: {
    [key: string]: TileLayer[];
  };
}): {
  visibleLayerName: vue20.Ref<string, string>;
};
// #endregion

// #region Variables
export declare const EPSG_3395: string;
export declare const EPSG_3857: string;
export declare const EPSG_4326: string;
export declare const OlMap: __VLS_WithSlots<typeof __VLS_component, __VLS_Slots>;
export declare const olMapInjectionKey: InjectionKey<Map>;
export declare const ONE_NM: number;
// #endregion

// #region Other
export { OLMap }
export { proj4 }
// #endregion